MAIN_STATE = 0
AUTHORIZATION_STATE = 1
TASKS_STATE = 2
# ENTER_ADDED_TASK_NAME_STATE = 1
# ENTER_ADDED_TASK_DATE_STATE = 2
# DELETE_TASK_STATE = 3
# RANDOM_TASK_STATE = 4
# ENTER_PRINT_TASKS_DATE_STATE = 5
